### ISSUE TITLE
Minor documentation fix: JAVA_HOME does not need to be setup if using the standalone ltex-ls version that includes java

### ISSUE THREAD

**Issue by rdiaz02** [emacs-languagetool/lsp-ltex#12]
Minor suggestion to the README.md, that says "P.S. LanguageTool is built with Java, make sure you have environment variable JAVA_HOME set up"

Actually, `lsp-ltex` runs just fine without setting JAVA_HOME if you download the standalone archives (for example, `ltex-ls-15.2.0-linux-x64.tar.gz` from https://github.com/valentjn/ltex-ls/releases/download/15.2.0/ltex-ls-15.2.0-linux-x64.tar.gz). I simply downloaded and decompressed under `~/.emacs.d/.cache/lsp/ltex-ls/` .

**Comment by jcs090218** [comment]
Don't remember why I added that documentation down there in the first place. Thanks!

Removed in 4377a8a344df47dba1cbaf26f67f1bf520976355.

**Comment by rdiaz02** [comment]
For completeness, I think you added the documentation because of this: https://github.com/emacs-languagetool/lsp-ltex/issues/2#issuecomment-863226627

I think one needs JAVA_HOME if ltex-ls does not come with Java bundled with it, but one does not need it if it comes with Java, as described in   https://valentjn.github.io/ltex/ltex-ls/installation.html:


  >  It’s recommended that you choose the archive corresponding to your platform (these archives are standalone, no Java installation necessary).
    If you choose the platform-independent file ltex-ls-VERSION.tar.gz, then you need Java 11 or later on your computer.

**Comment by jcs090218** [comment]
Sorry for not having all the note on the README. I'm quite busy recently, would you like to make contributions and open a PR for this? Appreciated if you would like to!

**Comment by rdiaz02** [comment]
I just did. What I wrote works for me under Linux (no idea about windows, though).
