### ISSUE TITLE
Suggestions offered by ltex-ls are not shown

### ISSUE THREAD

**Issue by rdiaz02** [emacs-languagetool/lsp-ltex#13]
ltex-ls often offers suggestions, but these are not shown by `lsp-ltex`.  For example, with a file that contains this

```
She go home
```

running `ltex-ls`  (actually, `ltex-cli`) from the command line will give

```
 The pronoun 'she' is usually used with a third-person or a past tense verb. [HE_VERB_AGR]
she go home
    Use 'goes'
    Use 'went'
```

However, in Emacs I do not see the suggestions for using "goes" or "went".
The following is a screen capture
![lsp](https://user-images.githubusercontent.com/1688611/147863939-0348866d-d7fc-4929-9b5b-c7e1a7e2249a.png)

**Comment by jcs090218** [comment]
What `lsp` frontend are you using?

If you are using `lsp-ui`, set `lsp-ui-sideline-show-code-actions` to `t` should do the trick.

**Comment by rdiaz02** [comment]
Thanks a lot. I was actually referring to the possible actions, like "Use 'goes" or "Use 'went'" not being shown in the flycheck errors buffer or on hovering with the mouse or in the minibuffer.  But yes, "Use 'goes'" and "Use 'went'" are shown as code actions.  

I guess this is how ltex-ls returns the result (I was used to textidote, that shows the "use goes", etc, in the flycheck buffer as well as on hovering and in the minibuffer).

So I think this is a misunderstanding on my part about how this was supposed to work. Sorry for the noise. Closing the issue.
