### ISSUE TITLE
Possible to read dictionary from file?

### ISSUE THREAD

**Issue by JoeyEremondi** [emacs-languagetool/lsp-ltex#16]
I'm wondering, is it possible to read a dictionary of spellcheck-words to ignore from a file?

I've tried using one in a .vscode directory (actually the one VSCode generates), since the ltex-ls docs seem to indicate it will look for that file automatically. But it doesn't seem to find it in emacs.

Ideally, it would also be possible to add words, like #4 is asking about.

Thanks!

**Comment by abougouffa** [comment]
Hello @JoeyEremondi, 

I've just commented on the original issue https://github.com/emacs-languagetool/lsp-ltex/issues/4#issuecomment-1204104692

Do you have any idea?

**Comment by abougouffa** [comment]
## 🔨  A dirty workaround! 

From my comment https://github.com/emacs-languagetool/lsp-ltex/issues/4#issuecomment-1204421857

For people with this same issue, here is my dirty workaround.

I found that, if I assign a word to the `lsp-ltex-dictionary`, it works, but with a file, it didn't. So I've fixed this by:

- Intercept the `lsp-execute-code-action`
- For the commands [`_ltex.addToDictionary`](https://valentjn.github.io/ltex/ltex-ls/server-usage.html#_ltexaddtodictionary-client), [`_ltex.disableRules`](https://valentjn.github.io/ltex/ltex-ls/server-usage.html#_ltexdisablerules-client) and [`_ltex.hideFalsePositives`](https://valentjn.github.io/ltex/ltex-ls/server-usage.html#_ltexhidefalsepositives-client)
 - Add the word to the corresponding pList `lsp-ltex-dictionary`, `lsp-ltex-disabled-rules` or `lsp-ltex-hidden-false-positives (not supported ATM)` respectively.
 - Serialize the modified variable by saving its content to a file under `user-emacs-directory` (`"lsp-ltex-dictionary.el"` ...).
 - At startup, load the content of the files if they exist to the corresponding variables.

I found also that [**these features needs to be implemented by the client**](https://valentjn.github.io/ltex/ltex-ls/server-usage.html#commands), I will try to rewrite this in a more generic way, and open a PR to be integrated with `lsp-ltex`, but until then, feel free to use this chunk in your config.

Hope it helps!

```elisp
(use-package lsp-ltex
  :init
  ;;; Some helper functions
  (defun +serialize-symbol (some-symbol)
    (when (boundp some-symbol)
      (let ((out-file (expand-file-name
                       (format "lsp-ltex/%s.el"
                               (symbol-name some-symbol))
                       user-emacs-directory)))
        (with-temp-buffer
          (prin1 (eval some-symbol)
                 (current-buffer))
          (write-file (expand-file-name out-file user-emacs-directory)))
        out-file)))

  (defun +deserialize-symbol (some-symbol)
    (let ((in-file (expand-file-name
                    (format "lsp-ltex/%s.el"
                            (symbol-name some-symbol))
                    user-emacs-directory)))
      (when (file-exists-p in-file)
        (message "Loading `%s' from file \"%s\"" (symbol-name some-symbol) in-file)
        (with-temp-buffer
          (insert-file-contents in-file)
          (goto-char (point-min))
          (ignore-errors (set some-symbol (read (current-buffer))))))))

  (defun +add-to-plist (lang word plist-symbol)
    (let* ((lang-key (make-symbol (concat ":" lang))))
      (when (null (eval plist-symbol))
        (set plist-symbol (list lang-key [])))
      (plist-put (eval plist-symbol) lang-key
                 (vconcat (list word) ;; Add word to the rest
                          (plist-get (eval plist-symbol) lang-key)))
      (+serialize-symbol plist-symbol)))

  ;;; The magic ---------------------------
  (defun +lsp-ltex--emulate-action (command lang element &optional title)
    (message "Emulating LSP action \"%s\" [%s], adding \"%s\"." title command element)
    (+add-to-plist
     lang element
     (cond ((equal command "_ltex.addToDictionary") 'lsp-ltex-dictionary)
           ((equal command "_ltex.disableRules") 'lsp-ltex-disabled-rules)
           ((equal command "_ltex.hideFalsePositives") 'lsp-ltex-hidden-false-positives))))

  (defun +lsp-ltex--execute-action (orig-fn &optional orig-args)
    (let* ((command-ht (gethash "command" orig-args))
           (command (gethash "command" command-ht))
           (title (gethash "title" command-ht))
           (arguments-ht (aref (gethash "arguments" command-ht) 0))
           (args-key (cond ((equal command "_ltex.addToDictionary") "words")
                           ((equal command "_ltex.disableRules") "ruleIds")
                           ((equal command "_ltex.hideFalsePositives") "falsePositives"))))
      (if (and args-key
               ;; TODO: The "falsePositives" case needs more processing,
               ;; it contains a string encoding a JSON object, needs to be extracted
               ;; and converted to the format `[:key "value"]' before serializing it.
               (not (equal args-key "falsePositives")))
          (let ((args-ht (gethash args-key arguments-ht)))
            (dolist (lang (hash-table-keys args-ht))
              (mapc
               (lambda (arg)
                 (+lsp-ltex--emulate-action command lang arg title))
               (gethash lang args-ht))))
        ;; For other actions, apply the original function call
        (apply orig-fn orig-args))))

  ;;; LTeX settings ---------------------------

  ;; Set LTeX LS variables
  (setq lsp-ltex-language "fr"
        lsp-ltex-mother-tongue "ar")

  ;; Load these LTeX LS variables from files
  (+deserialize-symbol 'lsp-ltex-dictionary)
  (+deserialize-symbol 'lsp-ltex-disabled-rules)
  (+deserialize-symbol 'lsp-ltex-hidden-false-positives)

  :config
  ;; Add our advice to `lsp-execute-code-action`
  (advice-add 'lsp-execute-code-action :around '+lsp-ltex--execute-action)

  :hook (text-mode . (lambda ()
                       (require 'lsp-ltex)
                       (lsp-deferred)))) ; or lsp
```

**Comment by ejuarezg** [comment]
Has anyone figured out how to read from a file? Or has this feature not been implemented yet? Just curious to know its state.

**Comment by jcs090218** [comment]
It's implemented in #26. Closing this issue now. ;)

**Comment by ejuarezg** [comment]
Since I'm not too familiar with emacs configuration, how would I go about adding a file as a dictionary?

**Comment by abougouffa** [comment]
@ejuarezg 

Theoretically, we can use such a file as a dictionary by setting the `lsp-ltex-dictionary` to the language and the file name, something like this:

```elisp
(setq lsp-ltex-dictionary
      '(:fr [":/home/hacko/.config/emacs/ltex-dict.french.txt"]
        :en [":/home/hacko/.config/emacs/ltex-dict.english.txt"]
        :ar [":/home/hacko/.config/emacs/ltex-dict.arabic.txt"]))
```

**However, the last time I've tested this it wasn't working**, I think it is a problem in the upstream `ltex-ls`, but I didn't figure out the real cause of the problem (see https://github.com/emacs-languagetool/lsp-ltex/issues/4#issuecomment-1204104692).

You can also set the list of words to add to the directory by modifying the `lsp-ltex-dictionary` value using for example:

```elisp
(setq lsp-ltex-dictionary
      '(:fr ["coplanarité" "neuromorphique"] :en ["photometrically" "neuromorphic"]))
```

Currently, `lsp-ltex` provide a workaround for adding words to a custom directory (via `code actions -> Add "word" to dictionary"`). However, the used format is not a text file with a word per line, but rather, an Emacs Lisp file representing the value of `lsp-ltex-dictionary`, following the same format as the code above:

```elisp
(:fr ["coplanarité" "neuromorphique"] :en ["photometrically" "neuromorphic"])
```

As a workaround, you can probably load the directory file elements and use it in the `lsp-ltex-directory` variable, using for example:

```elisp
(setq lsp-ltex-dictionary
      '(:en ; English
        (vconcat
         (string-lines
          (with-temp-buffer
            (insert-file-contents "path/to/your/custom/dictionary.english.txt")
            (buffer-string))))
        :fr ; French
        (vconcat
         (string-lines
          (with-temp-buffer
            (insert-file-contents "path/to/your/custom/dictionary.french.txt")
            (buffer-string))))))
```

I hope this answers your question!

**Comment by ejuarezg** [comment]
Thank you so much, @abougouffa !

I was able to use your code to load two different files for the same language.

```elisp
(setq lsp-ltex-dictionary
      `(:en ; English
        ,(vconcat
          (string-lines
           (with-temp-buffer
             (insert-file-contents "path/to/your/custom/dictionary.english.txt")
             (buffer-string))))
        :fr ; French
        ,(vconcat
          (string-lines
           (with-temp-buffer
             (insert-file-contents "path/to/your/custom/dictionary.french.txt")
             (buffer-string))))))
```
