### ISSUE TITLE
lsp-ltex with eglot?

### ISSUE THREAD

**Issue by maikol-solis** [emacs-languagetool/lsp-ltex#31]
It would be great if lsp-ltex could work with eglot, thinking that it will be merged into master anytime soon. 

Best.

**Comment by jcs090218** [comment]
There isn't much thing to show yet, but you can check out the [eglot-ltex](https://github.com/emacs-languagetool/eglot-ltex).

**Comment by maikol-solis** [comment]
Sorry for being so dumb. I hadn't checked the emacs-languagetool profile.

I close this issue for my own dignity.
