### ISSUE TITLE
Premium features

### ISSUE THREAD

**Issue by gour** [emacs-languagetool/lsp-ltex#32]
Hello,

can this package take advantage of LanguageTool's Premium features?

**Comment by jcs090218** [comment]
This is an question for the upstream language server (ltex), but I will answer it here.

Short answer, yes.

See https://valentjn.github.io/ltex/ltex-ls/changelog.html#1400-october-14-2021, try configure `lsp-ltex-languagetool-org-username` and `lsp-ltex-languagetool-org-api-key`.

**Comment by gour** [comment]
> This is an question for the upstream language server (ltex), but I will answer it here.
> 
> Short answer, yes.

Thank you!
