### ISSUE TITLE
`JAVA_HOME is not defined correctly` error with platform-dependent version 

### ISSUE THREAD

**Issue by luckysori** [emacs-languagetool/lsp-ltex#36]
I get the following error when opening a Markdown file:

```
Error: JAVA_HOME is not defined correctly.
  We cannot execute 

Process ltex-ls stderr finished
```

I've downloaded `ltex-ls-16.0.0-linux-x64.tar.gz` and extracted it in the right place, so I think it should work.

---

I'm on Ubuntu 22.04.2 LTS, on WSL2.

My config w.r.t. this package looks like this:

```emacs-lisp
(use-package
 lsp-ltex
 :hook
 (markdown-mode . lsp)
 (rst-mode . lsp)
 :init (setq lsp-ltex-version "16.0.0"))
 ```

**Comment by jcs090218** [comment]
I think you need to install JAVA. 🤔

**Comment by luckysori** [comment]
> I think you need to install JAVA. 🤔

Doesn't that contradict the README?

> As explained there, if you download the archive that corresponds to your platform, no Java installation is needed.

**Comment by luckysori** [comment]
You were right though, it was fixed my running `apt install openjdk-19-jdk ` ☺️

**Comment by jcs090218** [comment]
> Doesn't that contradict the README?

Yeah, I never tried install platform-dependent version so I am not quite sure if this is still true. 😅
