### ISSUE TITLE
Correct path for LTeX ?

### ISSUE THREAD

**Issue by raylemon** [emacs-languagetool/lsp-ltex#38]
I’m using Doom Emacs and I want to use LTeX on windows (native) and WSL.

On WSL, everything works fine. But on native, I can’t install ltex. I’ve downloaded the latest version, but I don’t know how to put files with new paths

I use the _.config_ structure, so

.config/doom for configuration files
.config/emacs for doom emacs

I’ve put LTeX in .local/cache, .local/cache/.cache, with **latest** or **ltex-1.6.0.0**, but none works. Any idea ?

**Comment by jcs090218** [comment]
I don't know about the .config structure, but this is my path under Windows 11:

```
C:\Users\username\AppData\Roaming\.emacs.d\.cache\lsp\ltex-ls\latest\
```

so my guess is:

```
C:\Users\username\AppData\Roaming\.config\.emacs.d\.cache\lsp\ltex-ls\latest\
```

**Comment by raylemon** [comment]
I have found when installing another LSP… It was at c:\users\username\.config\emacs\etc\lsp\ltex-ls\latest…

**Comment by raylemon** [comment]
I have found when installing another LSP… It was at c:\users\username.config\emacs\etc\lsp\ltex-ls\latest…
